name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -B clean install

      - name: Run tests
        run: mvn test

      # Upload JAR
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: iban-checker-jar
          path: target/*.jar

      # Upload JaCoCo Report
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      # Generate and Upload Javadoc
      - name: Generate Javadoc
        run: mvn javadoc:javadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: target/site/apidocs/

      # SpotBugs
      - name: Run SpotBugs
        run: mvn com.github.spotbugs:spotbugs-maven-plugin:4.7.3.4:check || true

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: target/spotbugsXml.xml
